---
- hosts: 192.168.80.30
  # become: yes
  tasks:
    - name: deploy container
      community.docker.docker_container:
        name: apache1
        image: httpd:alpine
        ports:
          - 80:80
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - /home/vagrant/resources/web-2/:/usr/local/apache2/htdocs
        # restart_policy: always
