---
- hosts: all
  become: yes
  tasks:

    - name: install prerequisites
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
        update_cache: yes
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable

    - name: install docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose
        update_cache: yes

    - name: add permissions
      shell: "usermod -aG docker vagrant"